### ISSUE TITLE
Broken with Trelamium

### ISSUE THREAD

**Issue by MeIsZ** [goldenapple3/OmniSwing#1]
I get this error when trying to load both OmniSwing and the Trelamium mod.

Object reference not set to an instance of an object.
   at Terraria.Projectile.SetDefaults(Int32 Type)
   at OmniSwing.SwingGlobalItem.ShouldAutoSwing(Item item)
   at OmniSwing.SwingGlobalItem.SetDefaults(Item item)
   at Terraria.ModLoader.ItemLoader.SetDefaults(Item item, Boolean createModItem)
   at Terraria.ModLoader.Mod.SetupContent()
   at Terraria.ModLoader.ModLoader.do_Load(Object threadContext)

**Comment by goldenapple3** [comment]
Fixed with 6f6d652
